### ISSUE TITLE
code？

### ISSUE THREAD

**Issue by TWJ718925** [dreasysnail/INSET#1]
Has the relevant code and data set been released recently?

**Comment by yichenhuang** [comment]
Dear TWJ718925,

Thanks for your interest in our work!

We are still preparing the code (and the dataset). We just released a demo for the tripadvisor dataset of hotel reviews so that you can get some intuitive understanding of our results. We plan to lease our checkpoint model in a week and our code in full in three weeks.

Best,
Yichen

**Comment by yichenhuang** [comment]
I close this issue because the code and dataset have been released.
