### ISSUE TITLE
Preprocessing/Tokenizing Code

### ISSUE THREAD

**Issue by x0w0** [dreasysnail/INSET#8]
Hi, thanks for the well-documented code. 
Can the code used for generating `sents_derep_bert_train_mask.json, sents_derep_bert_train.json, sents_derep_gpt_train.json, sents_derep_gpt_test.json, trip_cut_train_denoising.json, trip_derep_val.json` from `tripadvisor_review_processed_uncut.json` also be released?

**Comment by yichenhuang** [comment]
We do not plan to publicly release the code for generating sents_derep_bert_train_mask.json, sents_derep_bert_train.json, sents_derep_gpt_train.json, sents_derep_gpt_test.json, trip_cut_train_denoising.json, trip_derep_val.json. This is because the original dataset file tripadvisor_review_processed_uncut.json was not created or managed by us. Therefore, we cannot release the original dataset file. The code you requested relies on the original dataset file and cannot be directly run without the the original dataset file. However, if the code you requested is useful for your research, we are happy to send you the code via private communication. You might reach me at my email address in the paper.
